apiVersion: v1
kind: Service
metadata:
  name: k8s-eks-loadbalancer
  namespace: k8s-eks
  labels:
    app: k8s-eks-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: k8s-eks-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
