apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-config-map
  namespace: k8s
data:
  index.html: |
      <html>
      <body>
        <h1>Hello from k8s, and from Ricard :)!</h1>
      </body>
      </html>
